@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Databases/all.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Analytics/AzureEventHub.puml
!includeurl AzurePuml/Containers/AzureContainerApp.puml
!includeurl AzurePuml/Integration/AzureEventGrid.puml
!includeurl AzurePuml/Integration/AzureServiceBus.puml
!includeurl AzurePuml/Compute/AzureFunction.puml

System_Ext(systemExternalActors,"External Actors") {
    Person(personUser,"User")
    Container(compWebsite,"Website")
}
Container_Boundary(boundaryApi,"API") {
    Boundary(boundaryDataGatheringSubsystem,"Agent Subsystem") {
        AzureEventGrid(compEventGrid, "EventGrid","Publish")
        AzureServiceBus(compMessageQueue, "MessageQueue","Pub/Sub")
        AzureContainerApp(compInfoGatherer, "Information Gatherer Orchestrator","HTTPS")
        AzureContainerApp(compGardenOrgAgent, "GardenOrgAgent","DAPR")
        AzureContainerApp(compAgent2, "Agent 2","DAPR")
        AzureContainerApp(compAgent3, "Agent 3","DAPR")
    }
    AzureContainerApp(compSeedingService, "Initial Seeding Service","Container, C#")
    AzureContainerApp(compPlantQueryService, "PlantQueryService","Container, C#")
    AzureFunction(compPeriodicProcess, "PeriodicProcess","Azure function, C#","Every day?")
    Component_Ext(compWebInvokeGather,"Webhook")
    AzureCosmosDb(compReadModel, "Read Model","CosmosDB")
    Component_Ext(compDataStorreService,"DAPR DataStore Abstraction Service","DAPR")
}

Rel(compPlantQueryService,compDataStorreService,"dapr")
Rel(systemExternalActors,compPlantQueryService,"API Call")

Rel(compSeedingService, compEventGrid,"One time only – initiate info gathering for known list of initial terms")
Rel(compPeriodicProcess, compEventGrid,"push initiate gather message")
Rel(compEventGrid,compMessageQueue,"push message")
Rel(compMessageQueue, compInfoGatherer,"subscribes")
Rel(compWebInvokeGather,compInfoGatherer ,"webhook","manual invoke")
Rel(compInfoGatherer, compGardenOrgAgent,"dapr")
Rel(compInfoGatherer, compAgent2,"dapr")
Rel(compInfoGatherer, compAgent3,"dapr")

Rel(compGardenOrgAgent,compDataStorreService,"dapr")
Rel(compAgent2,compDataStorreService,"dapr")
Rel(compAgent3,compDataStorreService,"dapr")
Rel(compDataStorreService,compReadModel,"dapr")


@enduml