@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Ext(systemExternalActors,"External Actors") {
    Person(personUser,"User")
    Container(compWebsite,"Website")
}
Container_Boundary(boundaryApi,"API") {
    Boundary(boundaryDataGatheringSubsystem,"Agent Subsystem") {
        ComponentQueue(compEventGrid, "EventGrid","")
        ComponentQueue(compMessageQueue, "MessageQueue","Pub/Sub")
        Component(compInfoGatherer, "Information Gatherer Orchestrator","HTTPS")
        Component(compGardenOrgAgent, "GardenOrgAgent","DAPR")
        Component(compAgent2, "Agent 2","DAPR")
        Component(compAgent3, "Agent 3","DAPR")
    }
    Component(compSeedingService, "Initial Seeding Service","Container, C#")
    Component(compPlantQueryService, "PlantQueryService","Container, C#")
    Component(compPeriodicProcess, "PeriodicProcess","Azure function, C#","Every day?",$sprite="robot2")
    Component_Ext(compWebInvokeGather,"Webhook")
    ComponentDb(compReadModel, "ReadModel","CosmosDB")
    Component_Ext(compDataStorreService,"DAPR DataStore Abstraction Service","DAPR")
}

Rel(compPlantQueryService,compDataStorreService,"dapr")
Rel(systemExternalActors,compPlantQueryService,"API Call")

Rel(compSeedingService, compEventGrid,"One time only – initiate info gathering for known list of initial terms")
Rel(compPeriodicProcess, compEventGrid,"push initiate gather message")
Rel(compEventGrid,compMessageQueue,"push message")
Rel(compMessageQueue, compInfoGatherer,"subscribes")
Rel(compWebInvokeGather,compInfoGatherer ,"webhook","manual invoke")
Rel(compInfoGatherer, compGardenOrgAgent,"dapr")
Rel(compInfoGatherer, compAgent2,"dapr")
Rel(compInfoGatherer, compAgent3,"dapr")

Rel(compGardenOrgAgent,compDataStorreService,"dapr")
Rel(compAgent2,compDataStorreService,"dapr")
Rel(compAgent3,compDataStorreService,"dapr")
Rel(compDataStorreService,compReadModel,"dapr")


@enduml