name: Build Environment

# Manual trigger for now
on:  
  workflow_dispatch:
    paths-ignore:
      - 'infrastructure/**'
      - 'Design/**'

jobs:
  spinup:
    runs-on: windows-latest
    environment:
      name: DevTest
    env:
      ENVIRONMENT: dev
      RESOURCEGROUP: gardening
      AKSCLUSTERNAME: aksgardening
      DBNAME: glavgardendb
      DBCONTAINERNAME: glavgardenstage
      DBPRIMARYREGION: 'Australia East'
      AKSNODECOUNT: 2
    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Create Infrastructure
        uses: azure/powershell@v1
        with:
          inlineScript: |
            infrastructure/deploy.ps1 -Environment ${{ env.ENVIRONMENT }} -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID}} `
            -TenantId ${{ secrets.AZURE_TENANT_ID }} -ResourceGroupName ${{ env.RESOURCEGROUP}} -DbName ${{ env.DBNAME}} -DbContainerName ${{ env.DBCONTAINERNAME}} -DbPrimaryRegion "${{ env.DBPRIMARYREGION}}" `
            -AksClusterName ${{ env.AKSCLUSTERNAME }} -AksNodeCount ${{ env.AKSNODECOUNT }}
            
          azPSVersion: "latest"

      - name: Enable Dapr on AKS
        uses: azure/powershell@v1
        with:
          inlineScript: |
            infrastructure/enable-dapr-on-aks.ps1 -ResourceGroupName ${{ env.RESOURCEGROUP}} -AksClusterName ${{ env.AKSCLUSTERNAME }}
            
          azPSVersion: "latest"
