name: Build Environment

# Manual trigger for now
on:  
  workflow_dispatch:
    paths-ignore:
      - 'infrastructure/**'
      - 'Design/**'

jobs:
  spinup:
    runs-on: windows-latest
    environment:
      name: DevTest
    env:
      ENVIRONMENT: dev
      DBNAME: glavgardendb
      DBCONTAINERNAME: glavgardenstage
      DBPRIMARYREGION: 'Australia East'
    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Execute Infrastructure script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            infrastructure/deploy.ps1 -Environment ${{ env.ENVIRONMENT }} -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID}} `
            -TenantId ${{ secrets.AZURE_TENANT_ID }} -ResourceGroupName "gardening" -DbName ${{ env.DBNAME}} -DbContainerName ${{ env.DBCONTAINERNAME}} -DbPrimaryRegion "${{ env.DBPRIMARYREGION}}"
            
          azPSVersion: "latest"
#use az cli to build AKS -- will rsource gorup first